"""Evaluate the shipped classifier on the REAL, human-labelled validation set.

Run:  python -m src.validate_real      (also called by src.evaluate --report)

This is the project's headline result: synthetic test accuracy only shows the
pipeline works; accuracy on real bank strings shows whether the model does.

If data/real_validation.csv is missing, this prints SKIPPED and exits 0, so
the pipeline never blocks on labellers.

Rule fixed in advance (DECISIONS.md, pre-registration): nothing is tuned in
response to these numbers. The gap is reported, not closed.
"""
from __future__ import annotations

import json
import sys

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, recall_score

from src import config
from src.features import mask_digits


def run(synthetic_accuracy: float | None) -> dict:
    if not config.REAL_VALIDATION_CSV.exists():
        print("SKIPPED: data/real_validation.csv not found (labels not ingested yet). Real validation pending.")
        return {"status": "SKIPPED", "reason": "data/real_validation.csv not found"}

    bundle = joblib.load(config.CLASSIFIER_PATH)
    model, thr = bundle["pipeline"], bundle["abstain_threshold"]
    df = pd.read_csv(config.REAL_VALIDATION_CSV, dtype=str, keep_default_na=False)
    X, y = df["raw_string"], df["category"].to_numpy()
    proba = model.predict_proba(X)
    classes = np.array(model.classes_)
    pred, conf = classes[proba.argmax(axis=1)], proba.max(axis=1)
    correct = pred == y

    labels = [c for c in config.CATEGORY_NAMES if c in set(y)]
    acc = float(accuracy_score(y, pred))
    agreement = json.loads(config.LABEL_AGREEMENT_PATH.read_text()) if config.LABEL_AGREEMENT_PATH.exists() else {}
    ceiling = agreement.get("mean_pairwise_agreement")
    covered = conf >= thr
    out = {
        "status": "OK",
        "string_source": agreement.get("string_source", "unknown"),
        "n": int(len(df)),
        "accuracy": round(acc, 4),
        "macro_f1": round(float(f1_score(y, pred, labels=labels, average="macro", zero_division=0)), 4),
        "per_class_recall": {c: round(float(r), 4) for c, r in
                             zip(labels, recall_score(y, pred, labels=labels, average=None, zero_division=0))},
        "per_class_support": {c: int((y == c).sum()) for c in labels},
        "synthetic_test_accuracy": synthetic_accuracy,
        "generalisation_gap": None if synthetic_accuracy is None else round(synthetic_accuracy - acc, 4),
        "human_agreement": agreement,
        "human_ceiling_pairwise_agreement": ceiling,
        "accuracy_vs_ceiling": None if ceiling is None else round(acc - ceiling, 4),
        "abstain_threshold": thr,
        "coverage_at_threshold": round(float(covered.mean()), 4),
        "accuracy_on_covered": round(float(correct[covered].mean()), 4) if covered.any() else None,
    }

    lines = ["# Misclassified REAL strings, grouped by true category", "",
             f"Generated by `python -m src.evaluate --report`. Source: **{out['string_source']}**. "
             "Digits are masked (runs of 4+ digits → `#`).", ""]
    for cat in labels:
        m = (y == cat) & ~correct
        if not m.any():
            continue
        lines += [f"## {cat} ({int(m.sum())} wrong of {int((y == cat).sum())})", "",
                  "| string | predicted | confidence |", "|---|---|---|"]
        for s, p, c in sorted(zip(X[m], pred[m], conf[m]), key=lambda t: -t[2]):
            lines.append(f"| `{mask_digits(s).replace('|', '/')}` | {p} | {c:.3f} |")
        lines.append("")
    (config.RESULTS_DIR / "real_errors.md").write_text("\n".join(lines), encoding="utf-8")
    return out


def print_report(r: dict):
    if r["status"] != "OK":
        return
    print("\n=== REAL-DATA VALIDATION ===")
    if r["string_source"] != "real":
        print(f"!!! string source = {r['string_source']!r}: these are NOT real bank strings.")
    print(f"n={r['n']}  accuracy={r['accuracy']:.3f}  macro-F1={r['macro_f1']:.3f}")
    print(f"synthetic test accuracy={r['synthetic_test_accuracy']}  generalisation gap={r['generalisation_gap']}")
    print(f"human ceiling (mean pairwise agreement on anchors)={r['human_ceiling_pairwise_agreement']}  "
          f"Fleiss kappa={r['human_agreement'].get('fleiss_kappa')}")
    print(f"at abstain threshold {r['abstain_threshold']}: coverage={r['coverage_at_threshold']} "
          f"acc-on-covered={r['accuracy_on_covered']}")
    print("per-class recall: " + ", ".join(f"{c}={v:.2f}" for c, v in r["per_class_recall"].items()))


def main():
    metrics = json.loads(config.METRICS_PATH.read_text()) if config.METRICS_PATH.exists() else {}
    syn = metrics.get("classifier", {}).get("accuracy")
    r = run(syn)
    print_report(r)
    if metrics:
        metrics["real_validation"] = r
        config.METRICS_PATH.write_text(json.dumps(metrics, indent=2, sort_keys=False) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
